"use client";

import { useEffect } from "react";

const PAGEFIND_ELEMENT_ID = "pagefind-search-ui";

// Pagefind UI loads at runtime from /pagefind/pagefind-ui.{js,css}, which are
// generated by the `pagefind --site out` postbuild step (see package.json).
// Those files don't exist in `next dev`; the search box will render but show
// "loading…" indefinitely until a production build has run.
export default function PagefindSearch() {
  useEffect(() => {
    let cancelled = false;

    const stylesheet = document.createElement("link");
    stylesheet.rel = "stylesheet";
    stylesheet.href = "/pagefind/pagefind-ui.css";
    document.head.appendChild(stylesheet);

    const script = document.createElement("script");
    script.src = "/pagefind/pagefind-ui.js";
    script.onload = () => {
      if (cancelled) return;
      const W = window as unknown as {
        PagefindUI?: new (opts: Record<string, unknown>) => unknown;
      };
      if (typeof W.PagefindUI !== "function") return;
      new W.PagefindUI({
        element: `#${PAGEFIND_ELEMENT_ID}`,
        showSubResults: true,
        showImages: false,
        resetStyles: false,
        excerptLength: 30,
        debounceTimeoutMs: 250,
        translations: {
          placeholder: "Try 'profit margin', 'amazon fees', 'break-even'…",
          zero_results: "No results for [SEARCH_TERM]",
        },
      });
    };
    document.head.appendChild(script);

    return () => {
      cancelled = true;
      stylesheet.remove();
      script.remove();
    };
  }, []);

  return <div id={PAGEFIND_ELEMENT_ID} />;
}
