import { calcMeta } from "@/lib/calc-meta";
import { SITE_URL } from "@/lib/site";
import { toolBySlug } from "@/lib/tools";

type Props = { slug: string };

// "Save to Pinterest" CTA on every calc page. Opens Pinterest's create-pin
// dialog with the calc page URL, the per-calc 1000x1500 pin image, and a
// pre-filled description seeded from the calc's featuredAnswer.
//
// The pin images are generated by /pinterest-pin/[slug]/route.tsx as part
// of every build. The URL format follows Pinterest's documented widget API:
// https://help.pinterest.com/en/business/article/save-button
export default function PinterestSaveButton({ slug }: Props) {
  const tool = toolBySlug(slug);
  const meta = calcMeta(slug);
  if (!tool || !meta) return null;

  const pageUrl = `${SITE_URL}/${slug}`;
  const mediaUrl = `${SITE_URL}/pinterest-pin/${slug}`;
  // Pinterest descriptions cap around 500 chars; we keep ours short so the
  // user can edit it in the create-pin dialog without scrollback.
  const description = `${tool.name} — free, instant calculator for USA, UK, and South Africa businesses. ${meta.featuredAnswer}`.slice(
    0,
    480,
  );

  const pinterestUrl =
    `https://pinterest.com/pin/create/button/?url=${encodeURIComponent(pageUrl)}` +
    `&media=${encodeURIComponent(mediaUrl)}` +
    `&description=${encodeURIComponent(description)}`;

  return (
    <section className="mt-8 rounded-xl border border-gray-200 bg-white p-5">
      <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p className="text-sm font-semibold text-brand-dark">
            Found this calculator useful?
          </p>
          <p className="mt-1 text-sm text-gray-600">
            Save it to a Pinterest board for later, or share with your team.
          </p>
        </div>
        <a
          href={pinterestUrl}
          target="_blank"
          rel="noopener noreferrer"
          className="inline-flex items-center justify-center gap-2 rounded-md bg-[#E60023] px-4 py-2 text-sm font-semibold text-white hover:bg-[#AD081B]"
          aria-label={`Save ${tool.name} to Pinterest`}
        >
          <svg
            width="16"
            height="16"
            viewBox="0 0 24 24"
            fill="currentColor"
            aria-hidden
          >
            <path d="M12.017 0C5.396 0 .029 5.367.029 11.987c0 5.079 3.158 9.417 7.618 11.162-.105-.949-.199-2.403.041-3.439.219-.937 1.406-5.957 1.406-5.957s-.359-.72-.359-1.781c0-1.663.967-2.911 2.168-2.911 1.024 0 1.518.769 1.518 1.688 0 1.029-.653 2.567-.992 3.992-.285 1.193.6 2.165 1.775 2.165 2.128 0 3.768-2.245 3.768-5.487 0-2.861-2.063-4.869-5.008-4.869-3.41 0-5.409 2.562-5.409 5.199 0 1.033.394 2.143.889 2.741.099.12.112.225.085.345-.09.375-.293 1.199-.334 1.363-.053.225-.172.271-.402.165-1.495-.69-2.433-2.878-2.433-4.646 0-3.776 2.748-7.252 7.92-7.252 4.158 0 7.392 2.967 7.392 6.923 0 4.135-2.607 7.462-6.233 7.462-1.214 0-2.357-.629-2.748-1.378l-.748 2.853c-.271 1.043-1.002 2.35-1.492 3.146C9.57 23.812 10.763 24 12.017 24c6.624 0 11.99-5.367 11.99-11.988C24.007 5.367 18.641.001 12.017.001z" />
          </svg>
          Save to Pinterest
        </a>
      </div>
    </section>
  );
}
