export type BlogPost = {
  slug: string;
  title: string;
  description: string;
  keyword: string;
  category: "profit" | "pricing" | "operations" | "growth" | "people" | "investments";
  status: "published" | "draft";
  publishedAt?: string;
  lastModified?: string;
  related: string[];
};

// Site-wide last-modified date — bump this when articles are reviewed/refreshed
// rather than touching individual entries. Article schema uses this for
// dateModified, which Google rewards for freshness.
export const POSTS_LAST_REVIEWED = "2026-05-12";

export const POSTS: BlogPost[] = [
  { slug: "profit-margin-vs-markup-difference", title: "Profit Margin vs Markup: The Pricing Mistake That Loses Money", description: "Margin and markup aren't the same. Confusing them is a costly small-business pricing mistake — see the difference with worked examples.", keyword: "profit margin vs markup", category: "pricing", status: "published", publishedAt: "2026-05-11", lastModified: "2026-05-22", related: ["profit-margin-calculator", "markup-calculator", "pricing-calculator"] },
  { slug: "what-is-a-good-profit-margin", title: "What Is a Good Profit Margin for a Small Business?", description: "Industry benchmarks for gross and net margin — retail, services, SaaS, ecommerce — and how to know if yours is healthy.", keyword: "good profit margin small business", category: "profit", status: "published", publishedAt: "2026-05-11", related: ["profit-margin-calculator", "net-profit-calculator"] },
  { slug: "how-to-calculate-break-even-point", title: "How to Calculate Your Break-Even Point (With Examples)", description: "Step-by-step break-even analysis for any business — including the contribution-margin shortcut.", keyword: "how to calculate break-even point", category: "operations", status: "published", publishedAt: "2026-05-11", related: ["break-even-calculator", "cost-per-unit-calculator"] },
  { slug: "break-even-analysis-examples", title: "5 Break-Even Analysis Examples Across Different Industries", description: "Walk through real break-even calculations for a coffee shop, SaaS, ecommerce store, agency, and manufacturer.", keyword: "break-even analysis examples", category: "operations", status: "published", publishedAt: "2026-05-11", related: ["break-even-calculator"] },
  { slug: "how-to-calculate-roi-for-marketing", title: "How to Calculate Marketing ROI (And Why Most Get It Wrong)", description: "Marketing ROI is more than revenue divided by spend — here's how to track it accurately with attribution.", keyword: "marketing ROI calculation", category: "investments", status: "published", publishedAt: "2026-05-11", related: ["roi-calculator", "payback-period-calculator"] },
  { slug: "cost-plus-pricing-explained", title: "Cost-Plus Pricing: When to Use It, When to Avoid It", description: "Cost-plus is the simplest pricing method — and often the most dangerous. Here's when it works and when it loses money.", keyword: "cost plus pricing", category: "pricing", status: "published", publishedAt: "2026-05-11", lastModified: "2026-05-22", related: ["pricing-calculator", "markup-calculator"] },
  { slug: "value-based-pricing-vs-cost-plus", title: "Value-Based Pricing vs Cost-Plus: Which Should You Use?", description: "Cost-plus prices from the inside out; value-based prices from the customer's perspective. Here's how to choose.", keyword: "value based pricing", category: "pricing", status: "published", publishedAt: "2026-05-11", lastModified: "2026-05-22", related: ["pricing-calculator", "profit-margin-calculator"] },
  { slug: "how-much-to-charge-as-freelancer", title: "How Much Should I Charge as a Freelancer?", description: "From annual income target to hourly rate — including the tax buffer most freelancers forget.", keyword: "freelance hourly rate", category: "people", status: "published", publishedAt: "2026-05-11", related: ["freelance-rate-calculator", "invoice-calculator"] },
  { slug: "freelance-rates-by-industry-uk", title: "UK Freelance Rates by Industry (2026 Benchmarks)", description: "Typical day and hourly rates across design, dev, marketing, copywriting, and consulting in the UK.", keyword: "freelance rates UK", category: "people", status: "published", publishedAt: "2026-05-11", related: ["freelance-rate-calculator"] },
  { slug: "cash-flow-management-small-business", title: "Cash Flow Management for Small Business: A Practical Guide", description: "Why profitable businesses still go bust — and the seven habits that prevent a cash crunch.", keyword: "cash flow management small business", category: "operations", status: "published", publishedAt: "2026-05-11", related: ["cash-flow-calculator", "burn-rate-calculator"] },
  { slug: "gross-profit-vs-net-profit", title: "Gross Profit vs Net Profit: What's the Difference?", description: "Two profit numbers that mean very different things — and which one investors care about.", keyword: "gross profit vs net profit", category: "profit", status: "published", publishedAt: "2026-05-11", related: ["profit-margin-calculator", "net-profit-calculator"] },
  { slug: "ebitda-vs-net-profit", title: "EBITDA vs Net Profit: Which Number Actually Matters?", description: "EBITDA is the favourite of buyers; net profit is the favourite of owners. Here's why they differ.", keyword: "EBITDA vs net profit", category: "profit", status: "published", publishedAt: "2026-05-11", related: ["net-profit-calculator", "business-valuation-calculator"] },
  { slug: "amazon-fba-fees-explained", title: "Amazon FBA Fees Explained: What You Really Pay Per Sale", description: "Referral fees, fulfilment fees, storage, removal — a breakdown of every Amazon FBA cost with a profit example.", keyword: "Amazon FBA fees", category: "operations", status: "published", publishedAt: "2026-05-11", related: ["ecommerce-profit-calculator", "pricing-calculator"] },
  { slug: "etsy-seller-fees-explained", title: "Etsy Seller Fees Explained: The True Cost of Selling on Etsy", description: "Listing, transaction, payment, advertising — what Etsy actually takes from each sale.", keyword: "Etsy seller fees", category: "operations", status: "published", publishedAt: "2026-05-11", related: ["ecommerce-profit-calculator"] },
  { slug: "how-to-reduce-cost-per-unit", title: "7 Ways to Reduce Cost Per Unit in Your Business", description: "From bulk buying to automation to redesign — practical levers to drive down unit cost.", keyword: "reduce cost per unit", category: "operations", status: "published", publishedAt: "2026-05-11", related: ["cost-per-unit-calculator", "break-even-calculator"] },
  { slug: "how-business-loans-work", title: "How Business Loans Work: A Plain-English Guide", description: "Term loans, lines of credit, SBA loans, invoice finance — what they are and which suits which need.", keyword: "how business loans work", category: "investments", status: "published", publishedAt: "2026-05-11", related: ["business-loan-calculator", "cash-flow-calculator"] },
  { slug: "sba-loan-vs-conventional-loan", title: "SBA Loan vs Conventional Business Loan: Which Is Better?", description: "Lower rates and longer terms vs. faster approval and fewer hoops — here's the trade-off.", keyword: "SBA loan vs conventional", category: "investments", status: "published", publishedAt: "2026-05-11", related: ["business-loan-calculator"] },
  { slug: "startup-runway-burn-rate-guide", title: "Startup Runway and Burn Rate: The Founder's Guide", description: "How long is your runway, and how to extend it before fundraising becomes desperate.", keyword: "startup runway burn rate", category: "growth", status: "published", publishedAt: "2026-05-11", related: ["burn-rate-calculator", "cash-flow-calculator"] },
  { slug: "how-to-value-a-business-to-sell", title: "How to Value a Business to Sell: A 2026 Owner's Guide", description: "Three valuation methods, the multiples buyers actually use, and how to defend your asking price.", keyword: "how to value a business", category: "growth", status: "published", publishedAt: "2026-05-11", related: ["business-valuation-calculator", "net-profit-calculator"] },
  { slug: "revenue-growth-benchmarks", title: "Revenue Growth Benchmarks: What's Normal at Each Stage?", description: "Pre-seed to public — typical revenue growth rates and how to measure yours.", keyword: "revenue growth benchmarks", category: "growth", status: "published", publishedAt: "2026-05-11", related: ["revenue-growth-calculator", "business-valuation-calculator"] },
  { slug: "true-cost-of-an-employee", title: "The True Cost of an Employee (It's More Than the Salary)", description: "Payroll tax, benefits, equipment, training, overhead — the all-in cost of a hire and why it's usually 30-45% on top of salary.", keyword: "true cost of employee", category: "people", status: "published", publishedAt: "2026-05-11", related: ["employee-cost-calculator", "freelance-rate-calculator"] },
  { slug: "employee-vs-contractor-cost-comparison", title: "Employee vs Contractor: Which Costs Less?", description: "Side-by-side cost comparison for a typical $60k role — and when each makes sense.", keyword: "employee vs contractor cost", category: "people", status: "published", publishedAt: "2026-05-11", related: ["employee-cost-calculator", "freelance-rate-calculator"] },
  { slug: "payback-period-vs-roi", title: "Payback Period vs ROI: Which Should You Use?", description: "Payback measures speed of recovery; ROI measures total return. Here's when each matters more.", keyword: "payback period vs ROI", category: "investments", status: "published", publishedAt: "2026-05-11", related: ["payback-period-calculator", "roi-calculator"] },
  { slug: "uk-invoice-requirements", title: "UK Invoice Requirements: What Must Be on Every Invoice", description: "Legal requirements for UK invoices, VAT invoices, and what HMRC wants to see if you're audited.", keyword: "UK invoice requirements", category: "operations", status: "published", publishedAt: "2026-05-11", related: ["invoice-calculator", "freelance-rate-calculator"] },
  { slug: "discount-pricing-strategy", title: "Discount Pricing: When Discounts Help, When They Hurt", description: "Discounts can drive volume — or destroy your brand and your margin. Here's how to use them well.", keyword: "discount pricing strategy", category: "pricing", status: "published", publishedAt: "2026-05-11", related: ["discount-calculator", "pricing-calculator", "profit-margin-calculator"] },
];

export const PUBLISHED_POSTS = POSTS.filter((p) => p.status === "published");

export function postBySlug(slug: string): BlogPost | undefined {
  return POSTS.find((p) => p.slug === slug);
}
