import DsoCalculator from "@/components/calculators/DsoCalculator";
import CalculatorShell from "@/components/shared/CalculatorShell";
import FormulaBox from "@/components/shared/FormulaBox";
import FaqList from "@/components/shared/FaqList";
import RelatedTools from "@/components/shared/RelatedTools";
import Disclaimer from "@/components/shared/Disclaimer";
import MethodologyBox from "@/components/shared/MethodologyBox";
import WebAppSchema from "@/components/shared/WebAppSchema";
import HowToSchema from "@/components/shared/HowToSchema";
import { calculatorMetadata } from "@/lib/seo";
import { calcBreadcrumb, calcMeta } from "@/lib/calc-meta";

const SLUG = "dso-calculator";
const META = calcMeta(SLUG)!;

export const metadata = calculatorMetadata({
  slug: "dso-calculator",
  title: "DSO Calculator — Days Sales Outstanding & Cash Released | BusCalcTools",
  description:
    "Free Days Sales Outstanding calculator. Find your DSO, compare it to industry benchmarks, and see the cash you'd unlock by collecting faster.",
});

export default function DsoPage() {
  return (
    <CalculatorShell
      h1="DSO Calculator — Days Sales Outstanding & Cash Released"
      intro="Calculate how many days on average customers take to pay you — and how much cash a faster collections cycle would free up."
      breadcrumbs={calcBreadcrumb(SLUG)}
      slug={SLUG}
    >
      <WebAppSchema
        slug={SLUG}
        name="DSO Calculator"
        description="Free Days Sales Outstanding calculator with industry-benchmark comparison and cash-released estimate."
        featureList={META.featureList}
        applicationSubCategory={META.applicationSubCategory}
      />
      <HowToSchema
        slug={SLUG}
        name={META.howToName}
        description={META.howToDescription}
        steps={META.howToSteps}
      />
      <DsoCalculator />

      <section className="mt-10">
        <h2 className="text-lg font-semibold text-brand-dark">How it works</h2>
        <p className="mt-2 text-sm leading-relaxed text-gray-700">
          DSO is the ratio of accounts receivable to daily revenue. If you
          have $120,000 outstanding against $1.2M annual revenue, daily
          revenue is roughly $3,288 and DSO is 36.5 days — customers take
          an average of just over five weeks to pay. A 30-day benchmark is
          the convention because most B2B invoice terms are Net 30; anything
          materially above this is funded by your own cash or borrowing.
        </p>
        <p className="mt-2 text-sm leading-relaxed text-gray-700">
          The "cash tied up vs benchmark" figure quantifies the prize from
          accelerating collections. At $3,288 in daily revenue, every day
          shaved off DSO releases $3,288 in cash. Cutting DSO from 45 to 30
          days unlocks roughly $49,000 — usually achievable through prompt-pay
          discounts, automated reminders, or shifting to upfront milestone
          billing on longer projects.
        </p>
      </section>

      <section className="mt-10">
        <h2 className="text-lg font-semibold text-brand-dark">Common mistakes</h2>
        <ul className="mt-3 space-y-3 text-sm leading-relaxed text-gray-700">
          <li>
            <strong className="text-brand-dark">Using gross revenue including VAT or sales tax</strong> — DSO should be calculated on net revenue, the same basis as accounts receivable on most accounting systems. Mixing gross AR (which includes VAT) with net revenue overstates DSO by 15-20% depending on region. UK and SA businesses see the biggest distortion at 20% and 15% VAT.
          </li>
          <li>
            <strong className="text-brand-dark">Calculating DSO on annual revenue when the AR balance reflects only recent months</strong> — annualising a Q4 AR snapshot against full-year revenue understates DSO for fast-growing businesses, because most of the AR was generated by the higher recent run rate. Use trailing-90 revenue against current AR for a fairer match.
          </li>
          <li>
            <strong className="text-brand-dark">Treating one bad debtor as a DSO problem</strong> — a single 120-day-overdue customer in an otherwise prompt portfolio can push DSO by 5-10 days. The fix is collections action on that customer, not a portfolio-wide change to terms. Stratify AR by ageing band before deciding what to do.
          </li>
        </ul>
      </section>

      <section className="mt-10">
        <h2 className="text-lg font-semibold text-brand-dark">When to use this calculator</h2>
        <p className="mt-2 text-sm leading-relaxed text-gray-700">
          Use this monthly as a cash-flow vital sign, or before a working
          capital line review at the bank. A DSO trend rising 5+ days over a
          quarter is a leading indicator of cash pressure — usually showing
          up in late supplier payments and overdraft usage 60-90 days later
          if not addressed.
        </p>
        <p className="mt-2 text-sm leading-relaxed text-gray-700">
          For the full liquidity picture including current liabilities, use
          the Working Capital Calculator alongside this one. For a forward
          projection of how a DSO improvement flows into operating cash, use
          the Cash Flow Calculator.
        </p>
      </section>

      <FormulaBox>
        <pre className="whitespace-pre-wrap font-mono text-xs leading-relaxed">
{`DSO = (Accounts Receivable / Revenue) × Number of Days

Cash Tied Up vs Benchmark = AR − (Daily Revenue × 30)

Industry benchmarks (B2B):
  Services / SaaS:     30-45 days
  Manufacturing:       45-60 days
  Construction:        60-90 days
  Retail (B2C card):     1-3 days

Example: AR = $120,000 | Annual Revenue = $1,200,000
  Daily Revenue = $1.2M / 365 = $3,288
  DSO           = ($120,000 / $1.2M) × 365 = 36.5 days
  Cash tied up vs 30-day benchmark = $120,000 − ($3,288 × 30) = $21,360`}
        </pre>
      </FormulaBox>

      <section className="mt-10">
        <h2 className="text-lg font-semibold text-brand-dark">Worked example</h2>
        <p className="mt-2 text-sm leading-relaxed text-gray-700">
          A US digital agency hits $1.8M annual revenue with $295,000 in
          outstanding receivables at quarter-end. DSO = ($295,000 / $1,800,000)
          × 365 = 59.8 days. The owner has been wondering why the firm always
          feels cash-tight despite a healthy P&amp;L — this is why. Customers
          are taking nearly two months to pay against contractual Net 30 terms.
        </p>
        <p className="mt-2 text-sm leading-relaxed text-gray-700">
          Daily revenue is $4,932. Closing the gap to the 30-day benchmark
          would release $295,000 − ($4,932 × 30) = $147,040 in cash —
          immediately available to clear the firm&apos;s revolving line and
          stop the recurring overdraft fees. The math is far more compelling
          than any new-revenue push: collecting from existing customers is
          essentially zero-cost, while a $147,000 new-business win would
          require months of sales effort.
        </p>
        <p className="mt-2 text-sm leading-relaxed text-gray-700">
          The three levers, ranked by effort: First, automated invoice reminders
          at days 14, 21, and 28 — typically drops average DSO by 5-8 days
          inside one quarter. Second, a 1.5% prompt-pay discount for under-15-day
          settlement — switches the cost-benefit for finance teams at the
          customer end. Third, restructure new contracts to 40% upfront, 40%
          milestone, 20% on completion — eliminates the timing risk on roughly
          half the revenue. Combined, these typically take DSO from the
          high-50s down to 35-40 days within two quarters.
        </p>
      </section>

      <FaqList items={META.faqs} />

      <section className="mt-12">
        <h2 className="text-lg font-semibold text-brand-dark">Glossary</h2>
        <dl className="mt-3 space-y-3 text-sm text-gray-700">
          <div>
            <dt className="font-semibold text-brand-dark">DSO</dt>
            <dd>Days Sales Outstanding — the average number of days between issuing an invoice and collecting payment.</dd>
          </div>
          <div>
            <dt className="font-semibold text-brand-dark">Accounts Receivable (AR)</dt>
            <dd>Money owed to your business by customers for goods or services already delivered, still awaiting payment.</dd>
          </div>
          <div>
            <dt className="font-semibold text-brand-dark">Net 30</dt>
            <dd>Standard B2B payment term — invoice is due 30 days from issue date. DSO above 30 means customers are paying later than contractually required.</dd>
          </div>
        </dl>
      </section>

      <RelatedTools
        slugs={["working-capital-calculator", "cash-flow-calculator", "invoice-calculator"]}
      />

      <MethodologyBox slug={SLUG} />

      <Disclaimer />
    </CalculatorShell>
  );
}
